### ISSUE TITLE
Not working on dynamically loaded content

### ISSUE THREAD

**Issue by Kryptonit3** [egoist/vue-timeago#79]
Does not update on dynamically loaded content. I paginate data and update with axios. My ajax data contains new timestamps. The html of the timestamp is updating just not the `timeago` functionality. Only way around it currently is to set `:auto-update="1"` on the `timeago` elements.

How can I reload timeago after ajax data loading?

**Comment by samvaughton** [comment]
Also getting this issue, will try to investigate when I get a chance

**Comment by samvaughton** [comment]
Ok, so on the `render` function just using the already computed variable of `timeago` does not work. Changing it to re-compute on re-render seems to do the trick although on `data` the `timeago` variable never changes regardless. Maybe this component is best suited as a filter?

You can find the changes I applied myself here: https://github.com/samvaughton/vue-timeago/commit/b3ec472af488abce7a041237e401c7e52c84c8c2

I can submit a PR if you'd like but I'm not sure what to do with the data variable as it does not get updated. I don't know enough about Vue at the moment to fully understand why the value is not updating automatically.

** update ** I assumed that the `data.timeago` did not update due to it being computed once on initialization - so I changed it to a computed property and reverted those changes and it now also works. I'm not sure which is the best method.

Here is the computed version:

```
computed: {
      timeago: function () {
        return this.convert(this.since)
      }
    },
    render: function render(h) {
      return h('time', {
        attrs: {
          datetime: new Date(this.since),
          title: typeof this.title === 'string' ? this.title : this.title === false ? null : this.timeago
        }
      }, [this.timeago]);
    },
```

**Comment by atef201080** [comment]
I'm having the same issue and it's really annoying.
